export enum textTypes {
  TITLE_BOLDE = 'TITLE_BOLDE', //24PX
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_lIGHT = 'TITLE_lIGHT',
  SUB_TITLE_BOLDE = 'SUB_TITLE_BOLDE', //20PX
  SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
  SUB_TITLE_lIGHT = 'SUB_TITLE_lIGHT',
  BUTTON_BOLDE = 'BUTTON_BOLDE', //18PX
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_lIGHT = 'BUTTON_lIGHT',
  PARAGRAPH_BOLDE = 'PARAGRAPH_BOLDE', //14PX
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
  PARAGRAPH_lIGHT = 'PARAGRAPH_lIGHT',
  PARAGRAPH_SMALL_BOLDE = 'PARAGRAPH_SMALL_BOLDE', //10PX
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
  PARAGRAPH_SMALL_lIGHT = 'PARAGRAPH_SMALL_lIGHT',
}
