export enum buttonConst{
    BUTTON_DEFAULT = 'BUTTON_DEFAULT',
    BUTTON_SECONDARY = 'BUTTON_SECONDARY',
    BUTTON_LOADING = 'BUTTON_LOADING',
    BUTTON_DISABLE = 'BUTTON_DISABLE',
    BUTTON_TITLE = 'BUTTON_TITLE',
  }